Exception Summary: Another band-aid for missing stacktrace (#17)
* summary: another band-aid for missing stacktrace

The following error was reported:

	UndefVarError: `bt` not defined

Previously, a different error was reported where bt was a 0-length
vector. Why the stacktrace is missing is not known in either case.